### PR TITLE
adds HTML message on 'no such service' exception when connection via CAS

### PR DESCRIPTION
**Pull request by LucasTrg**
The StateT enum has been expanded to provide a new state that can be interpreted by Angular. I kept it very straightforward and barebones so that it behaves consistently with the way the other messages do.

### CODE REVIEW

**Comment by tharvik** [comment]
Travis gives
> ERROR: /home/travis/build/c4dt/omniledger/webapp/src/app/api/v0/cas/login/login.component.ts[24, 20]: Missing trailing comma

We've enabled some formatting to help with code consistency, you can run `npx ng lint --fix` to automatically fixes thoses

Otherwise, the PR LGTM, congrats for your first contribution to omnilegder :)

**Comment by LucasTrg** [comment]
I'm not sure if the automatic check need resolving as I see that other PRs suffer from it too, please notify me if I need to look deeper into it !

**Comment by tharvik** [comment]
Ho, right, there is a deps on https://github.com/qantik/qrgo which is gone. @ineiti do you know of another QRcode library that we can use?

**Comment by ineiti** [comment]
dedis/cothority#2435

**Comment by tharvik** [comment]
It seems that there is another formatter/linter failing. In this repo, we actually use `ng lint` to tare care of typescript and `prettier` to take care of the HTML. The latter is failing now, can you fix it please?

**Review by ineiti — APPROVED** [review]
Once the tests pass I'm OK.

**Comment by ineiti** [comment]
Re-run `npm run lint:fix` in `webapp`

**Pull request merged**
